-- 코드를 작성해주세요
SELECT ed0.ID, IFNULL(ed3.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ed0 LEFT JOIN (SELECT ed1.ID, COUNT(ed1.ID) AS CHILD_COUNT
            FROM ECOLI_DATA ed1 JOIN ECOLI_DATA ed2 ON ed1.ID= ed2.PARENT_ID
            GROUP BY ed1.ID) ed3 ON ed0.ID = ed3.ID