SELECT fo.PRODUCT_ID, fp.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS fo
    JOIN FOOD_PRODUCT AS fp ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE
    fo.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY fo.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID