-- 코드를 작성해주세요
SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM (SELECT it.ITEM_ID
    FROM (SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE') iid JOIN ITEM_TREE it ON iid.ITEM_ID = it.PARENT_ITEM_ID) iti JOIN ITEM_INFO ii ON iti.ITEM_ID = ii.ITEM_ID
ORDER BY ITEM_ID DESC