-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, b.MAX_SIZE - a.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA a JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) As MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) b
WHERE YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR(a.DIFFERENTIATION_DATE), YEAR_DEV, ID;