SELECT TITLE, USED_GOODS_REPLY.BOARD_ID, REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, TO_CHAR(USED_GOODS_REPLY.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_REPLY JOIN USED_GOODS_BOARD ON (USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID)
WHERE EXTRACT(YEAR FROM USED_GOODS_BOARD.CREATED_DATE) = 2022 AND EXTRACT(MONTH FROM USED_GOODS_BOARD.CREATED_DATE) = 10
ORDER BY USED_GOODS_REPLY.CREATED_DATE, TITLE